In [1]:
import numpy as np

In [2]:
list1  =  [1,2,3,4,5,6,7,8,9]
arr = np.array(list1)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
type(arr)

numpy.ndarray

2d list


In [4]:
list2 = [[1,2,3],[4,5,6],[7,8,9]]
list2[1][1]
arr = np.array(list2)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

2.Using arange


In [5]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

3. Specify types of array

Zero arrays

In [14]:
arr = np.zeros(5)
arr
# Array always return by default float 



array([0., 0., 0., 0., 0.])

In [15]:
# there a way to convert
array = np.zeros(5, dtype=int)
array

array([0, 0, 0, 0, 0])

In [16]:
arr = np.zeros((5,5),int )
arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

Identity matrix


In [18]:
arr = np.eye(4,dtype="int")
arr

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

4. Using Linspace

linspace is a function in Numpy library that generate a sequence of numbers. It is used to create an array of evenly spaced numbers over a specified range

Syntax:
 numpy.linspace(start, stop, num = 50)

In [19]:
arr = np.linspace(1,5)
arr

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [21]:
arr = np.linspace(1,2,5)
arr

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

5.Random NUmbers

In [ ]:
# random functions from 1 to 5
arr = np.random.rand(5)
arr

array([0.05739632, 0.24215353, 0.6652324 , 0.80218076, 0.07684085])

In [24]:
# if you gave two variables then it will be consider as row and columns
arr = np.random.rand(5,5)
arr

array([[0.84931014, 0.36087111, 0.60242531, 0.85301572, 0.83163217],
       [0.90438715, 0.01504056, 0.47359006, 0.09106948, 0.59813321],
       [0.73886803, 0.8853158 , 0.62405676, 0.82546774, 0.42094112],
       [0.56933319, 0.00195846, 0.39165231, 0.55732431, 0.87716919],
       [0.07465641, 0.98094868, 0.80908686, 0.35292254, 0.423519  ]])

In [25]:
# Randint function is used to generate random numbers from the range of number first is starting
# and second is ending and third is how many to generate 

arr = np.random.randint(1,50,10)
arr

array([25, 12, 12, 17, 41, 26, 41, 39, 31, 22])

In [ ]:
# generate random numbers near to 0 and negative

arr = np.random.randn(1,2)
arr

array([[-0.37301623,  1.95870201]])

In [30]:
arr = np.random.randn(5)
arr

array([ 0.20916845, -0.51717123,  0.08250544,  1.00152505,  0.16909457])

In [32]:
arr = np.random.randn(2,2,3)
arr

array([[[-0.24931495, -2.0473163 ,  0.72385937],
        [ 0.47178337,  0.48918128, -0.45104357]],

       [[ 0.85565244, -0.3079874 , -0.81147349],
        [-2.61572954,  0.24488996,  0.17475275]]])

6. Structured array

In [46]:
arr = np.array([(1, "khurram", 18), (2, "rafay", 22), (3, "uzair", 20)], 
               dtype=[("id", int), ("name", "U10"), ("age", int)])
print(arr)

[(1, 'khurram', 18) (2, 'rafay', 22) (3, 'uzair', 20)]


In [47]:
arr["name"]
arr["id"]
arr["age"]

array([18, 22, 20])

In [42]:
arr = np.array([(1, "khurram", 18), (2, "rafay", 22), (3, "uzair", 20)], 
               dtype="object")
arr

array([[1, 'khurram', 18],
       [2, 'rafay', 22],
       [3, 'uzair', 20]], dtype=object)

In [39]:
arr[1][1]

'rafay'